### ISSUE TITLE
`internal` packages

### ISSUE THREAD

**Issue by dhiaayachi** [golang/oscar#7]
I have a question about the current packages structure and the use of `internal` to host all the packages. Is that temporary until the API is mature enough to be used externally or for some other reason? 

In case it's temporary, what are the expectations before it's moved to be non `internal`?

Based of the README and the project announcement Oscar is meant to be a framework/library to build maintainer's bots and not a specific implementation of that bot, gaby. Is my understanding right?

**Comment by ianlancetaylor** [comment]
Yes, using `internal` is what we are doing for now.  And, yes, the goal is a framework that other projects can use as well.

Because the Go project in general is careful about backward compatibility, making packages publicly visible means committing to an API.  Keeping the packages in internal lets everybody experiment before we commit.  Right now we only have one tool for one project; that's not enough to show that our APIs are good.
